"""empty message

Revision ID: 79562126ca80
Revises: c9d495fee8ba
Create Date: 2022-01-20 05:39:29.765269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79562126ca80'
down_revision = 'c9d495fee8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_subscribe_order_types', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bot_view_multi_post_order_types', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('bot_view_one_post_order_types', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_view_one_post_order_types', 'active')
    op.drop_column('bot_view_multi_post_order_types', 'active')
    op.drop_column('bot_subscribe_order_types', 'active')
    # ### end Alembic commands ###
