"""empty message

Revision ID: b852df10c58f
Revises: 
Create Date: 2022-01-12 22:54:59.164930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b852df10c58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_users', sa.Column('adb_balanse', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_users', 'adb_balanse')
    # ### end Alembic commands ###
