"""empty message

Revision ID: c9d495fee8ba
Revises: b852df10c58f
Create Date: 2022-01-16 06:46:14.646263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d495fee8ba'
down_revision = 'b852df10c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_admins_user_id_fkey', 'bot_admins', type_='foreignkey')
    op.create_foreign_key(None, 'bot_admins', 'bot_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('bot_referals_referal_user_id_fkey', 'bot_referals', type_='foreignkey')
    op.drop_constraint('bot_referals_referal_for_user_id_fkey', 'bot_referals', type_='foreignkey')
    op.create_foreign_key(None, 'bot_referals', 'bot_users', ['referal_for_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bot_referals', 'bot_users', ['referal_user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('user_balanse_change_hystory', sa.Column('count', sa.Float(), nullable=True))
    op.drop_constraint('user_balanse_change_hystory_user_id_fkey', 'user_balanse_change_hystory', type_='foreignkey')
    op.create_foreign_key(None, 'user_balanse_change_hystory', 'bot_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_balanse_change_hystory', type_='foreignkey')
    op.create_foreign_key('user_balanse_change_hystory_user_id_fkey', 'user_balanse_change_hystory', 'bot_users', ['user_id'], ['user_id'])
    op.drop_column('user_balanse_change_hystory', 'count')
    op.drop_constraint(None, 'bot_referals', type_='foreignkey')
    op.drop_constraint(None, 'bot_referals', type_='foreignkey')
    op.create_foreign_key('bot_referals_referal_for_user_id_fkey', 'bot_referals', 'bot_users', ['referal_for_user_id'], ['user_id'])
    op.create_foreign_key('bot_referals_referal_user_id_fkey', 'bot_referals', 'bot_users', ['referal_user_id'], ['user_id'])
    op.drop_constraint(None, 'bot_admins', type_='foreignkey')
    op.create_foreign_key('bot_admins_user_id_fkey', 'bot_admins', 'bot_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
