"""empty message

Revision ID: dcd027edc639
Revises: 79562126ca80
Create Date: 2022-01-21 04:28:53.445693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcd027edc639'
down_revision = '79562126ca80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_price_param', sa.Column('first_lvl_referal_balanse_percent', sa.Float(), nullable=True))
    op.add_column('bot_price_param', sa.Column('first_lvl_referal_work_percent', sa.Float(), nullable=True))
    op.add_column('bot_price_param', sa.Column('second_lvl_referal_balanse_percent', sa.Float(), nullable=True))
    op.add_column('bot_price_param', sa.Column('second_lvl_referal_work_percent', sa.Float(), nullable=True))
    op.add_column('bot_users', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('bot_users', 'adb_balanse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_users', sa.Column('adb_balanse', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('bot_users', 'create_date')
    op.drop_column('bot_price_param', 'second_lvl_referal_work_percent')
    op.drop_column('bot_price_param', 'second_lvl_referal_balanse_percent')
    op.drop_column('bot_price_param', 'first_lvl_referal_work_percent')
    op.drop_column('bot_price_param', 'first_lvl_referal_balanse_percent')
    # ### end Alembic commands ###
